### ISSUE TITLE
Unknown option: direct.minified

### ISSUE THREAD

**Issue by jwoertink** [babel/ruby-babel-transpiler#292]
I'm looking at these options https://babeljs.io/docs/usage/options/ and I see a `minified` option. My code looks like

``` ruby
source = "let a = 1;"
Babel::Transpiler.transform(source, 'minified' => true)
```

The error is

``` text
ExecJS::ProgramError: ReferenceError: [BABEL] unknown: Unknown option: direct.minified
Logger.error ((execjs):8951:11)
OptionManager.mergeOptions ((execjs):9459:29)
OptionManager.init ((execjs):9549:10)
File.initOptions ((execjs):8189:75)
new File ((execjs):8179:22)
Pipeline.transform ((execjs):13511:16)
eval (eval at <anonymous> ((execjs):67512:8), <anonymous>:1:18)
(execjs):67512:8
(execjs):67518:14
self ((execjs):1:102)
/Users/jeremywoertink/.rvm/gems/ruby-2.3.0/gems/execjs-2.7.0/lib/execjs/external_runtime.rb:39:in `exec'
/Users/jeremywoertink/.rvm/gems/ruby-2.3.0/gems/execjs-2.7.0/lib/execjs/external_runtime.rb:21:in `eval'
/Users/jeremywoertink/.rvm/gems/ruby-2.3.0/gems/execjs-2.7.0/lib/execjs/external_runtime.rb:46:in `call'
/Users/jeremywoertink/.rvm/gems/ruby-2.3.0/gems/babel-transpiler-0.7.0/lib/babel/transpiler.rb:28:in `transform'
```

**Comment by tricknotes** [comment]
https://babeljs.io is described about Babel 6 however this gem uses Babel 5.
Your option is supported since Babel 6.

If you want to minify you code, please use minifier such as [UglifyJS](https://github.com/mishoo/UglifyJS) or its [Ruby wrapper](https://github.com/lautis/uglifier).
